### ISSUE TITLE
need java 15 support

### ISSUE THREAD

**Issue by Domaman202** [Yamakaja/class-hacking#2]

**Comment by Yamakaja** [comment]
Hey, this repo was only intended to demonstrate what's clearly a hack, highly implementation specific and can't reasonably be supported.

**Comment by Domaman202** [comment]
kk

**Comment by Domaman202** [comment]
where did you get the offets?

**Comment by Yamakaja** [comment]
These were extracted from the OpenJDK klass.hpp. The old offsets can be found here: https://gist.github.com/0x277F/33b14fe2d8fc29735a2873fcd04b48ea

The header for jdk15: https://hg.openjdk.java.net/jdk/jdk15/file/0dabbdfd97e6/src/hotspot/share/oops/klass.hpp

**Comment by Domaman202** [comment]
thx
